### ISSUE TITLE
Input/Output for Knapsack

### ISSUE THREAD

**Issue by purpl3F0x** [kostis/ntua_compilers#33]
Is there any example input/output for `knapsack.alan` ? 
(for us - the hardware guys - that don't even know the algorithm 👉👈)

**Comment by purpl3F0x** [comment]
@andreasstamos is your algorithm correct ? I tried some inputs from [geek4geeks](https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/),  and in the 1st input it gives 9 instead of 3. I get 9 from both the python implementation of the PR and the alan one.

Sample code:
https://onlinegdb.com/Ry8zi4lmH

**Comment by purpl3F0x** [comment]
Okay, I found the issue. I hadn't notice you give are reading the weight first. I am getting the correct results now.

So some test cases, can be:
```
In::
  3
  50
  10
  20
  30
  60
  100
  120
Out:
  220
```
```
In:
  3
  4
  4
  5
  1
  1
  2
  3
Out:
  3
```

**Comment by purpl3F0x** [comment]
Also, a recursive version of the algorithm in alan

```r
main () : proc

	knapsack(n: int, w_max: int, w: reference int [], v: reference int []) : int
		dp : int[10000];
		i : int;
		w_c : int;
	{
		w_c = 0;
		while (w_c <= w_max) {
			dp[w_c] = 0;
			w_c = w_c+1;
		}
		i = 0;
		while (i < n) {
			w_c = w_max;
			while (w_c > 0) {
				if (w[i] <= w_c & v[i] + dp[w_c-w[i]] > dp[w_c])
					dp[w_c] = v[i] + dp[w_c-w[i]];
				w_c = w_c - 1;
			}
			i = i+1;
		}
		return dp[w_max];
	}

	w : int[10000];
	v : int[10000];
	n : int;
	w_max : int;
	res : int;
	i : int;

{ -- main
	n = readInteger();
	w_max = readInteger();

	if (n <= 0) return;

	i = 0;
	while (i < n) {
		w[i] = readInteger();
		i = i+1;
	}

	i = 0;
	while (i < n) {
		v[i] = readInteger();
		i = i+1;
	}

	res = knapsack(n, w_max, w, v);

	writeInteger(res);
	writeChar('\n');
} -- main
```

**Comment by kostis** [comment]
> Is there any example input/output for `knapsack.alan` ?

I will add one.  The random testing infrastructure is a cute / great idea but it's not a substitute for one or two unit tests.

>  (for us - the hardware guys - that don't even know the algorithm 👉👈)

Don't worry, nobody is perfect :-)  

> @andreasstamos is your algorithm correct ? I tried some inputs from geek4geeks, and in the 1st input it gives 9 instead of 3. I get 9 from both the python implementation of the PR and the alan one.

Apparently, you hardware guys (also) have some trouble finding the correct order of the input :P  However, perhaps it's a good idea to use the geek4geeks ordering (and better names for the arrays) in the program's source.  Will do that change.

**Comment by purpl3F0x** [comment]
I'm closing the issue, since it's mostly addressed.

It would be good, for some tests to be added, for the newly added alan programs, that don't have a grace equivalent.
