### ISSUE TITLE
Possible issue in cancer.alan

### ISSUE THREAD

**Issue by purpl3F0x** [kostis/ntua_compilers#41]
I think,
there is an issue in [cancer.alan](https://github.com/kostis/ntua_compilers/blob/master/alan/programs/cancer.alan).

At the main function, there is an "strlen" algorithm that calculates the String length "n", then decrements the value by 1. (lines 24-26).

Then n gets passed along the sting to `cancer()` and gets reduced again.

This will make only strings like  "annaX" pass, instead of "anna"

**Comment by kostis** [comment]
Thanks for the issue.  Actually, I had already noticed this and had fixed it in my checked out version of the repository.

@purpl3F0x : can you please double check the #42 PR?

**Comment by purpl3F0x** [comment]
> @purpl3F0x : can you please double check the #42 PR?

Yes, it seems to be working, as intended.
Issue can be closed, as soon as the PR is merged.


```bash
> ./test_cancer.exe
Give a string with maximum length 30: anna
anna ... is palindrome

> ./test_cancer.exe
Give a string with maximum length 30: anNna
anNna ... is palindrome

> ./test_cancer.exe
Give a string with maximum length 30: bob          
bob ... is palindrome

> ./test_cancer.exe
Give a string with maximum length 30: alice
alice ... is not palindrome

> ./test_cancer.exe
Give a string with maximum length 30: anna  #<---has trailing space
anna  ... is not palindrome

```
