### ISSUE TITLE
[Edsger] Possible overflow in `brainduck.eds`

### ISSUE THREAD

**Issue by nikgalanop** [kostis/ntua_compilers#8]
In `brainduck.eds` and specifically in the function `void decrement_ptr()`, in order to achieve circular shifting, I've written the following update rule on the `aidx` variable (of type `int`): 
```
aidx = (30000 + aidx - 1) % 30000;
```
According to the Edsger specification, integers are signed and 2 bytes long, meaning that the max positive value that can be stored is `32768`. The offset of `30000` makes this `aidx` update susceptible to overflows.

Should I change this computation to the equivalent form:
```
if (aidx == 0) aidx = 29999;
else aidx = (aidx - 1) % 30000;
```
or leave it the way it currently is?

**Comment by kostis** [comment]
I think it's better to change it to the equivalent form.  Also, perhaps leave a comment there why it is written that way.
Thanks for the contribution of this program, by the way!
